### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [AMDESE/sev-tool#19]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [Command::pdh_cert_export](https://github.com/AMDESE/sev-tool/blob/3109b4a2ceb075e8f468033788c0bdc70fff0c4d/src/commands.cpp#L136)
- [SEVDevice::create_ovmf_var_file](https://github.com/AMDESE/sev-tool/blob/a3647d53947760b9290d2c3fbeef3f2f7bde2cf3/src/sevcore_linux.cpp#L562)

**Comment by ldeweysuse** [comment]
Originally smart pointers were not utilized because C++ wrappers haven't been written for the C libraries being used by the sev-tool. The sevapi.h library was designed to remain [purely C](https://github.com/AMDESE/sev-tool/blob/master/src/sevapi.h#L21), and the stat struct is also C. I am in agreement. It would be really nice to utilize smart pointers to make sure memory is cleaned up.
