### ISSUE TITLE
Clarify Digest & context

### ISSUE THREAD

**Issue by rgentz** [AMDESE/sev-tool#41]
Hello Sev team,

I am looking at the calc measurement function. 

Could you clarify what digest & context is and where I can get this information? 

Further I would like to ask if mnonce from the sev_measurement is the same as the nonce from the generate_launch_blob function?

**Comment by jpecholt** [comment]
Hey,
for the first generation of SEV, the digest is quite easy. I ran through an example in [this issue](https://github.com/AMDESE/sev-tool/issues/44). The important points are:
- Every value must be hex-encoded
- The context always remains 04, there is no change to that (it's something alike to an API command reference number, and in this case we always want to calculate the measurement)
- The SEV policy must be the same as the one used during VM launch
- For SEV, the digest consists of a SHA256 over the OVMF_CODE.fd/OVMF.bin you used during VM launch. For SEV-ES, there may be additional content that flows into the digest which I'm not too familiar with unfortunately
- The TIK is the latter half of the tpm_tk.bin file, we must convert it to hex
- API major and minor as well as the build are returned in decimal if you obtained them using the `--platform_status` command. They must be hex-encoded.
- For the nonce, you have to obtain the "launch measure" from the SEV firmware - if you use QEMU, look at the [query-sev-launch-measure](https://qemu.readthedocs.io/en/latest/interop/qemu-qmp-ref.html#id467) QMP command. Why I used quotation marks in this case is because the returned value contains both the actual launch measure and the nonce that was used to create it. The measure is the first 32 bytes, the nonce is the rest.

I am working on a [pull request](https://github.com/AMDESE/sev-tool/pull/38) which expands the current Readme to contain more information, maybe there are some pointers that help you.

**Comment by larrydewey** [comment]
@rgentz I believe @jpecholt provided a thorough response to your question. If there is additional follow-up to this issue, feel free to re-open it.
