### ISSUE TITLE
export_cert_chain_vcek: parsing of tcb_version bogus

### ISSUE THREAD

**Issue by haraldh** [AMDESE/sev-tool#48]
https://github.com/AMDESE/sev-tool/blob/8b9c3ecb4f4a2c9eac90c4b5722382852ab44f52/src/sevcore_linux.cpp#L1277-L1281

1. it could query the tcb_version with the SNP_PLATFORM_STATUS.
2. if does not convert hex to decimal for the URL, where decimal is expected
3. it expects the tcb_version in reverse byte order.

**Comment by larrydewey** [comment]
@haraldh I believe #61 should have addressed this issue.

That being said, there is sometimes an issue which occurs after performing an upgrade to FW version 1.51 which may cause a TCB version mismatch. If this happens, the best way to mitigate the issue is to manually reload the `kvm_amd` kernel module and `CCP` driver without performing an OS restart.

```zsh
# Manually unload the kvm_amd kernel module and CCP driver.
sudo modprobe -r kvm_amd

# Verify the CCP driver is no longer loaded or running (should have no output)
lsmod | grep ccp

# Manually reloads the CCP driver, then the kvm_amd kernel module, causing the
# FW to update again and fix the problem.
sudo modprobe kvm_amd
```
